proyecto_tienda/ofertas/urls.py
from django.urls import path
from . import views

app_name='ofertas'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear_oferta/', views.crear_o_editar_oferta, name='crear_oferta'),
    path('editar_oferta/<int:oferta_id>/', views.crear_o_editar_oferta, name='editar_oferta'),
    path('eliminar_oferta/<int:oferta_id>/', views.eliminar_oferta, name='eliminar_oferta'),
]

proyecto_tienda/productos/urls.py
from django.urls import path
from . import views

app_name='productos'

urlpatterns= [
    path('', views.index, name='index'),
]

proyecto_tienda/proyecto_tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include ('productos.urls')),
    path('ofertas/', include(('ofertas.urls', 'ofertas'), namespace='ofertas')), #agregué 'ofertas' y el namespace para que encuentre bien la ruta
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('ordenes/', include(('ordenes.urls', 'ordenes'), namespace='ordenes')),
]

proyecto_tienda/usuarios/urls.py
from django.urls import path
from . import views


app_name= 'usuarios'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('cerrar_sesion/', views.logout_view, name='cerrar_sesion'),
    path('inicio_sesion/', views.login_view, name='login'),
]

proyecto_tienda/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Principal{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Mi Tienda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'productos:index'  %}">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ofertas:index' %}">Ofertas</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuarios:cerrar_sesion' %}">Cerrar Sesión</a>
                        </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                    </li>
                    {% endif %}

                </ul>
                <span class="navbar-text">
                    Hola, {{ user.username }}
                </span>
            </div>
        </div>
    </nav>
    
    <!--Contenido Principal-->
    <div class="container mt-4">
        {% if messages %}
        <div>
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
        {%endif%}
        {% block content %} {% endblock %}
    </div>
    
    
    <script>
        window.addEventListener("beforeunload", function(){
            navigator.sendBeacon("{% url 'usuarios:cerrar_sesion' %}");
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js'%}"></script>
</body>
</html>

proyecto_tienda/templates/index.html
{% extends 'base.html'%}

{% block title %} Página Principal {% endblock %}

{% block content%}

<header class="text-center">
    <h1>PÁGINA PRINCIPAL</h1>
</header>

<div class="jumbotron bg-light p-5 rounded mt-4">
    <div class="row"> 
        <div class="col-lg-8 col-md-10 col-sm-12 mx-auto text-center">
            <h2 class="display-4">Bienvenido a Nuestra Tienda</h2>
            <p class="lead">Explora nuestra selección de productos y ofertas</p>
            <hr class="my-4">
            <p>Haz clic en los enlaces de arriba para ir a nuestras categorías</p>
            <button id="show-alert" class="btn btn-warning btn-lg btn-block">Presiona Aquí</button>
        </div>
    </div>
</div>
<nav class="text-center">
    <a class="btn btn-primary" href="{% url 'productos:index' %}">IR A PRODUCTOS</a>
    <a class="btn btn-secondary" href="{% url 'ofertas:index' %}">IR A OFERTAS</a>
</nav>
{% endblock %}