proyecto_tienda/ofertas/urls.py
from django.urls import path
from . import views

app_name='ofertas'

urlpatterns = [
    path('', views.index, name='index'),
    path('crear_oferta/', views.crear_o_editar_oferta, name='crear_oferta'),
    path('editar_oferta/<int:oferta_id>/', views.crear_o_editar_oferta, name='editar_oferta'),
    path('eliminar_oferta/<int:oferta_id>/', views.eliminar_oferta, name='eliminar_oferta'),
]

proyecto_tienda/ordenes/urls.py
from django.urls import path
from . import views

app_name = 'ordenes'

urlpatterns = [
    path('', views.ver_ordenes, name='ver_ordenes'),
    path('crear/', views.crear_orden, name='crear_orden'),
    path('eliminar/<int:orden_id>/', views.eliminar_orden, name='eliminar_orden'),
    path('editar/<int:orden_id>/', views.editar_orden, name='editar_orden'),
]

proyecto_tienda/proyecto_tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include ('productos.urls')),
    path('ofertas/', include(('ofertas.urls', 'ofertas'), namespace='ofertas')), #agregué 'ofertas' y el namespace para que encuentre bien la ruta
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('', views.index, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('ordenes/', include(('ordenes.urls', 'ordenes'), namespace='ordenes')),
]

proyecto_tienda/ordenes/models.py
from django.db import models
from productos.models import Producto

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    
    def __str__(self):
        return self.nombre

class Orden(models.Model):
    n_orden = models.AutoField(primary_key=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha_orden = models.DateTimeField(auto_now=True)
    
    def save(self, *args, **kwargs): #sobreescribe un método en este caso Orden sobre escribe models con los datos que le damos
        self.precio_unitario = self.producto.precio
        self.total = self.precio_unitario*self.cantidad
        super().save(*args, **kwargs) #es una forma para pasar cualquier cantidad de argumentos sin tener q definirlos especificamente, al guardarlos
        
    def __str__(self):
        return f'N° orden: {self.n_orden}, Producto: {self.producto.nombre}'    

proyecto_tienda/ordenes/forms.py
from django import forms
from .models import Orden
from productos.models import Producto
from .models import Cliente

class OrdenForm(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['producto', 'cantidad', 'cliente']
        producto = forms.ModelChoiceField(queryset=Producto.objects.all(), empty_label='Seleccione un producto')# el queryset es como decir SELECT * FROM en la bbdd (nos muestra todos los registros)
        cantidad = forms.IntegerField(min_value=1, initial=1)
        cliente  = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label='Seleccione un cliente')
        

proyecto_tienda/ordenes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import OrdenForm
from .models import Orden

# Create your views here.
def crear_orden(request):
    if request.method == 'POST':
        form = OrdenForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ordenes:ver_ordenes')
    else:
        form = OrdenForm()
    return render(request, 'ordenes/crear_orden.html', {'form':form})

def editar_orden(request, orden_id):
    orden = get_object_or_404(Orden, pk=orden_id)

    if request.method == 'POST':
        form = OrdenForm(request.POST, instance=orden)
        if form.is_valid():
            form.save()
            return redirect('ordenes:ver_ordenes')
    else:
        form = OrdenForm(instance=orden)
    return render(request, 'ordenes/crear_orden.html', {'form':form})

def eliminar_orden(request, orden_id):
    orden = get_object_or_404(Orden, pk = orden_id)

    if request.method == 'POST':
        orden.delete()
        return redirect('ordenes:ver_ordenes')
    return render(request, 'ordenes/eliminar_orden.html', {'orden': orden})

def ver_ordenes(request):
    ordenes = Orden.objects.all()
    return render(request, 'ordenes/ver_ordenes.html', {'ordenes': ordenes})

proyecto_tienda/ordenes/templates/ordenes/crear_orden.html
{% extends 'base.html'%}

{% block title %} CREAR ORDEN {% endblock %}

{% block content %}
    <h2>{% if form.instance.pk %} Editar {% else %} Crear {% endif %} Orden </h2>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn bg-primary">Enviar</button>
    </form>

{% endblock %}

proyecto_tienda/ordenes/templates/ordenes/eliminar_orden.html
{% extends 'base.html' %}

{% block title %} ELIMINAR ORDEN {% endblock %}

{% block content %}
    <h2>¿Está seguro de eliminar la orden {{orden.nombre}}?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn bg-danger">Eliminar</button>
    </form>
<br>
<a href="{% url 'ordenes:ver_ordenes'%}" class=" btn bg-warning"> Cancelar</a>

{% endblock %}

proyecto_tienda/ordenes/templates/ordenes/ver_ordenes.html
{% extends 'base.html'%}

{% block title %} VER ORDEN {% endblock %}

{% block content %}

    <h2>Listado de Ordenes</h2>
    {% if ordenes %}
        <table>
            <thead>
                <tr>
                    <th>N° Orden</th>
                    <th>Cliente</th>
                    <th>Producto</th>
                    <th>Cantidad</th>
                    <th>Acción 1</th>
                    <th>Acción 2</th>
                </tr>
            </thead>
            <tbody>
                {% for orden in ordenes %}
                <tr>
                    <td>{{ orden.n_orden }}</td>
                    <td>{{ orden.cliente }}</td>
                    <td>{{ orden.producto }}</td>
                    <td>{{ orden.cantidad }}</td>
                    <td><a href="{% url 'ordenes:editar_orden' orden.pk %}">Editar</a></td>
                    <td><a href="{% url 'ordenes:eliminar_orden' orden.pk %}">Eliminar</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No hay productos disponibles </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>No hay Ordenes</p>
    {% endif %}  
    
{% endblock %}    